SQLALCHEMY_DATABASE_URI: sqlite:///${PROJECT_ROOT}/mockapi.db
SQLALCHEMY_TRACK_MODIFICATIONS: False
SQLALCHEMY_ECHO: False
SECRET_KEY: "\xac\xc8\x05\xc2N'\xa3kuA\xdb\x80\xa1\xf7\x11\xfa" # MUST BE CHANGED!
FLASK_ADMIN_SWATCH: cerulean
