"""namespace.path is unique field

Revision ID: 50a7c4a2797a
Revises: 99e2d5e8e71f
Create Date: 2019-04-08 15:03:25.250399

"""
from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a7c4a2797a'
down_revision = '99e2d5e8e71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('namespace', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f('uq_namespace_path'), ['path']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('namespace', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('uq_namespace_path'), type_='unique'
        )

    # ### end Alembic commands ###

