"""Initial rev. of MockEndpoint

Revision ID: 617a635358a4
Revises: 
Create Date: 2018-11-09 21:47:55.585740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617a635358a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'mock_endpoint',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=80), nullable=False),
        sa.Column('uri', sa.String(length=255), nullable=False),
        sa.Column('method', sa.String(length=10), nullable=True),
        sa.Column('response_body', sa.Text(), nullable=True),
        sa.Column('response_type', sa.String(length=100), nullable=True),
        sa.Column('response_code', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mock_endpoint')
    # ### end Alembic commands ###
