"""add namespaces support

Revision ID: 99e2d5e8e71f
Revises: 617a635358a4
Create Date: 2019-04-08 14:58:11.598860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e2d5e8e71f'
down_revision = '617a635358a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mock_endpoint', schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f('fk_mock_endpoint_namespace_id_namespace'),
            'namespace',
            ['namespace_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mock_endpoint', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('fk_mock_endpoint_namespace_id_namespace'),
            type_='foreignkey'
        )

    # ### end Alembic commands ###
