"""add enabled field

Revision ID: a19e13ee4573
Revises: 50a7c4a2797a
Create Date: 2019-04-08 16:11:46.231007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19e13ee4573'
down_revision = '50a7c4a2797a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mock_endpoint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mock_endpoint', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
